### ISSUE TITLE
TSEnumDeclaration

### ISSUE THREAD

**Issue by okevinok** [baozouai/babel-plugin-enum-to-object#2]
![image](https://github.com/baozouai/babel-plugin-enum-to-object/assets/19623957/ba6b275c-386c-4830-a169-d818a0817da0)
无法进入 TSEnumDeclaration 观察者函数，Identifier 是可以进入的。

**Comment by baozouai** [comment]
> ![image](https://user-images.githubusercontent.com/19623957/253883935-ba6b275c-386c-4830-a169-d818a0817da0.png) 无法进入 TSEnumDeclaration 观察者函数，Identifier 是可以进入的。

<img width="937" alt="image" src="https://github.com/baozouai/babel-plugin-enum-to-object/assets/33510001/9bfb09c1-c02e-4d58-b4c2-8c1643de7314">

可以进啊，不然怎么起作用

**Comment by okevinok** [comment]
能否提供一个最小实现，在我的项目里使用 存在问题，webpack 4 , vue2, node16

**Comment by okevinok** [comment]
是不是与 typescript 版本有关系

**Comment by baozouai** [comment]
> 能否提供一个最小实现，在我的项目里使用 存在问题，webpack 4 , vue2, node16

项目里有test呀，不然你console.log看有没有进去就知道了

**Comment by baozouai** [comment]
> 能否提供一个最小实现，在我的项目里使用 存在问题，webpack 4 , vue2, node16

存在问题是说这插件不起作用，还是什么

**Comment by okevinok** [comment]
typescript 3.7.4  
![image](https://github.com/baozouai/babel-plugin-enum-to-object/assets/19623957/815d907b-5c35-44c8-a61f-72d5da9e0035)

下面的Identifier 是没问题的，能进的

**Comment by baozouai** [comment]
> typescript 3.7.4 ![image](https://user-images.githubusercontent.com/19623957/254596776-815d907b-5c35-44c8-a61f-72d5da9e0035.png)
> 
> 下面的Identifier 是没问题的，能进的

麻烦提供一个最小复现，如github链接

**Comment by okevinok** [comment]
![image](https://github.com/baozouai/babel-plugin-enum-to-object/assets/19623957/9bbd82c1-4fba-4c64-b16a-5f3628d5fd24)

https://github.com/EvinqWang/vue-cli-webpack

**Comment by baozouai** [comment]
> ![image](https://user-images.githubusercontent.com/19623957/254755686-9bbd82c1-4fba-4c64-b16a-5f3628d5fd24.png)
> 
> [EvinqWang/vue-cli-webpack](https://github.com/EvinqWang/vue-cli-webpack)

我看进来的时候已经被处理成js了，所以导致TSEnumDeclaration进不来了，猜测可能是被某个loader提前处理了
<img width="1627" alt="image" src="https://github.com/baozouai/babel-plugin-enum-to-object/assets/33510001/c8c4d26a-897a-4ff4-92cb-625a64a82148">

**Comment by okevinok** [comment]
我该怎么把这个babel 处理 前置呢，在webpack项目中

**Comment by baozouai** [comment]
> 我该怎么把这个babel 处理 前置呢，在webpack项目中

暂时不知道如何处理，vue的我不太熟，等我有空再尝试解决，但确实没前置处理，不过你可以尝试写个处理ts的loader，应用该plugin来处理code，输出新的code

**Comment by okevinok** [comment]
解决了，但是似乎转成对象之后 ，打包还是会包含很多 没用使用到的属性呢，树摇这个能力现在是没有，还是我使用的姿势不对呢。

**Comment by baozouai** [comment]
> 解决了，但是似乎转成对象之后 ，打包还是会包含很多 没用使用到的属性呢，树摇这个能力现在是没有，还是我使用的姿势不对呢。

怎么解决的，没shaking？有转成const obj吗

**Comment by okevinok** [comment]
![image](https://github.com/baozouai/babel-plugin-enum-to-object/assets/19623957/ccfc6a83-99ea-4c86-9b25-749e6f21da8f)
 编译后的参产物是这样的。禁用了vue-cli的ts-loader ，使用babel进行编译，然后调整插件顺序

**Comment by baozouai** [comment]
> ![image](https://user-images.githubusercontent.com/19623957/254910275-ccfc6a83-99ea-4c86-9b25-749e6f21da8f.png) 编译后的参产物是这样的。禁用了vue-cli的ts-loader ，使用babel进行编译，然后调整插件顺序

可以将改动push到你哪个git仓库，我看看

**Comment by okevinok** [comment]
已经提交，build之后看 index,js中的枚举的产物即可

**Comment by baozouai** [comment]
> 已经提交，build之后看 index,js中的枚举的产物即可

我看即使打印了一个obj某个属性，其他的也都会打包进去，估计还是vue-loader转换过程中发生了啥

<img width="629" alt="image" src="https://github.com/baozouai/babel-plugin-enum-to-object/assets/33510001/4ee804d2-459e-413a-b9a1-303704431e45">


<img width="970" alt="image" src="https://github.com/baozouai/babel-plugin-enum-to-object/assets/33510001/0cf0abc7-37e6-46d6-9d4e-1ab2eaed1e73">

**Comment by okevinok** [comment]
我该怎么去分析，或者说实现（被标记的）对象，实现未使用到的属性，实现树摇，能给个大方向? 对这方面不是太熟悉，要向大佬学习

**Comment by baozouai** [comment]
> 我该怎么去分析，或者说实现（被标记的）对象，实现未使用到的属性，实现树摇，能给个大方向? 对这方面不是太熟悉，要向大佬学习

你得看vue-loader转成了啥，因为我在.vue里面用obj，也是全部打包进去了，所以要看vue-loader的产物

**Comment by okevinok** [comment]
好的 ，谢谢大哥
