### ISSUE TITLE
引入项目后无报错但不生效

### ISSUE THREAD

**Issue by Magicalboys** [baozouai/babel-plugin-enum-to-object#3]
babel.config.json 文件如下
{
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "enum-to-object",
      {
        "reflect": true // 默认值 代表需要反射值
      }
    ]
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-typescript",
    [
      "@babel/preset-react",
      {
        // 自动导入 JSX 转换而来的函数
        "runtime": "automatic"
      }
    ]
  ]
}

是哪里打开方式不对吗

**Comment by baozouai** [comment]
@Magicalboys 给一个最小复现demo

**Comment by Magicalboys** [comment]
方便加wx吗 ：magicalyao

**Comment by baozouai** [comment]
> 方便加wx吗 ：magicalyao

@Magicalboys 可以加我，baozouai
